---
sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - FEATURE_FLAG=''
  - FEATURE_FLAG='--features gsl'
addons:
  apt:
    packages:
      - libgsl-dev

before_script:
  - rustup component add rustfmt-preview

script:
  - "[ '$TRAVIS_RUST_VERSION' != 'nightly' ] || cargo fmt --all -- --check"
  - cargo build --all $FEATURE_FLAG
  - cargo test --all $FEATURE_FLAG

cache: cargo

#  vim: set ts=2 sw=2 tw=0 et :
